### ISSUE TITLE
Note: Colloquium will be on June 29th at 11:00am EST. You're invited. 

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/thesis#43]
Yes, I mean you. Comment here if you'd like to come.

**Comment by RichardLitt** [comment]
Hi there, 

Richard Littauer is inviting you to a scheduled Zoom meeting. 

Topic: Richard Littauer's Thesis Colloqium: OSS for Low Resource Languages
Time: Jun 29, 2018 11:00 AM Eastern Time (US and Canada)

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/193506503

Or iPhone one-tap :
    US: +19294362866,,193506503#  or +16699006833,,193506503# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 193 506 503
    International numbers available: https://zoom.us/u/eBihWPglj

**Comment by alvations** [comment]
Oh that early! Better finish my comments on the thesis over the weekend =)

**Comment by RichardLitt** [comment]
Alright! Starts in two hours.

**Comment by RichardLitt** [comment]
This was done! Video here: https://www.youtube.com/watch?v=p-LM4XnURCU
